database1:
  driver: mysql
  #source: root:lcc_cn2580946@tcp(39.107.141.185:3306)/seckill?charset=utf8&loc=Asia%2FShanghai&parseTime=true
  source: root:root@tcp(127.0.0.1:3306)/seckill?charset=utf8&loc=Asia%2FShanghai&parseTime=true #parseTime=true => 不配置go time.Time无法解析Mysql的datatime时间

redis:
  addr: 39.107.141.185:6379
  db: 0
  poolsize: 600
  min-idle-conns: 10

rabbitmq:
  addr: amqp://guest:guest@39.107.141.185:5672/my_vhost #连接信息amqp://kuteng:kuteng@127.0.0.1:5672/kuteng 这个信息是固定不变的amqp://事固定参数后面两个是用户名密码ip地址端口号Virtual Host
  queue: seckillQueue
  exchange: seckillExchange

web:
  post: :9090